# Generated by Django 4.2.7 on 2023-12-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
